#!/usr/bin/env node
/**
 * Generate supabase/seed.sql from a content export (JSON array of items).
 *
 * Pipeline:  Content Studio → "Export JSON" → this script → supabase/seed.sql
 *
 * Usage:
 *   node scripts/content/generate-seed.mjs [input.json] [output.sql]
 *   # defaults: ./learnquest-content.json  →  supabase/seed.sql
 *
 * Only `published` items are emitted (items without a status are treated as
 * published). Columns match the base `questions` table in supabase/schema.sql.
 */
import { readFileSync, writeFileSync } from "node:fs";
import { resolve } from "node:path";

const input = process.argv[2] || "learnquest-content.json";
const output = process.argv[3] || "supabase/seed.sql";

let items;
try {
  const raw = JSON.parse(readFileSync(resolve(input), "utf8"));
  items = Array.isArray(raw) ? raw : [raw];
} catch (err) {
  console.error(`✗ Could not read/parse ${input}: ${err.message}`);
  process.exit(1);
}

const published = items.filter((i) => !i.status || i.status === "published");

const s = (v) => (v == null ? "null" : `'${String(v).replace(/'/g, "''")}'`);
const j = (v) => (v == null ? "null" : `'${JSON.stringify(v).replace(/'/g, "''")}'::jsonb`);
const enumv = (v, type) => (v == null ? "null" : `'${String(v).replace(/'/g, "''")}'::${type}`);
const num = (v, d = 0) => (v == null || Number.isNaN(Number(v)) ? d : Number(v));

const cols =
  "id, subject, strand_id, age_band, level, type, difficulty, prompt, passage, options, tokens, answer, explanation, xp, coins";

const rows = published.map((q) =>
  "  (" +
  [
    s(q.id),
    enumv(q.subject, "subject_id"),
    s(q.strandId ?? q.strand_id),
    enumv(q.ageBand ?? q.age_band, "age_band"),
    num(q.level, 1),
    enumv(q.type, "activity_type"),
    num(q.difficulty, 1),
    s(q.prompt),
    s(q.passage),
    j(q.options),
    j(q.tokens),
    j(q.answer),
    s(q.explanation),
    num(q.xp, 10),
    num(q.coins, 3),
  ].join(", ") +
  ")",
);

const sql = `-- ════════════════════════════════════════════════════════════════════════
--  LearnQuest content seed — generated by scripts/content/generate-seed.mjs
--  Source: ${input}   ·   ${published.length} published item(s)
--  Run after supabase/schema.sql.
-- ════════════════════════════════════════════════════════════════════════

insert into questions (${cols})
values
${rows.join(",\n")}
on conflict (id) do update set
  subject = excluded.subject,
  strand_id = excluded.strand_id,
  age_band = excluded.age_band,
  level = excluded.level,
  type = excluded.type,
  difficulty = excluded.difficulty,
  prompt = excluded.prompt,
  passage = excluded.passage,
  options = excluded.options,
  tokens = excluded.tokens,
  answer = excluded.answer,
  explanation = excluded.explanation,
  xp = excluded.xp,
  coins = excluded.coins;
`;

writeFileSync(resolve(output), sql, "utf8");
console.log(`✓ Wrote ${published.length} item(s) to ${output}`);
